In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#define vocabulary size
voc_size=10000

In [7]:
##one hot representation

# one_hot() is used ONLY to convert words → integer indices.
# Embedding layer cannot work on strings.It requires integer indices.
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9430, 1797, 411, 1766],
 [9430, 1797, 411, 1049],
 [9430, 6378, 411, 9992],
 [8749, 774, 6932, 7856, 8538],
 [8749, 774, 6932, 7856, 7214],
 [7169, 9430, 2035, 411, 2364],
 [2316, 1641, 2990, 7856]]

In [8]:
##word embedding representation
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [11]:
#pad_sequence is require to convert all input sentences of the same length

sent_len=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 9430 1797  411 1766]
 [   0    0    0    0 9430 1797  411 1049]
 [   0    0    0    0 9430 6378  411 9992]
 [   0    0    0 8749  774 6932 7856 8538]
 [   0    0    0 8749  774 6932 7856 7214]
 [   0    0    0 7169 9430 2035  411 2364]
 [   0    0    0    0 2316 1641 2990 7856]]


In [13]:
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 338ms/step


array([[[ 0.04155034,  0.00710474, -0.02148788,  0.02141143,
          0.00745738,  0.00914507,  0.02824235,  0.04480488,
          0.00997654, -0.01211794],
        [ 0.04155034,  0.00710474, -0.02148788,  0.02141143,
          0.00745738,  0.00914507,  0.02824235,  0.04480488,
          0.00997654, -0.01211794],
        [ 0.04155034,  0.00710474, -0.02148788,  0.02141143,
          0.00745738,  0.00914507,  0.02824235,  0.04480488,
          0.00997654, -0.01211794],
        [ 0.04155034,  0.00710474, -0.02148788,  0.02141143,
          0.00745738,  0.00914507,  0.02824235,  0.04480488,
          0.00997654, -0.01211794],
        [-0.00691068, -0.00930297,  0.01104878, -0.01775037,
         -0.01419175,  0.00311238, -0.01070135,  0.02402851,
         -0.01341516,  0.03017279],
        [-0.03541623, -0.01467049, -0.02990416, -0.02293689,
         -0.04085872, -0.00155973, -0.00610082,  0.04883398,
          0.04534172, -0.03874699],
        [-0.03569193,  0.03248659, -0.02242576,  0.0